// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmhucr-oLHywGBbbPx_8LeqKAT8uHDsmI',
    appId: '1:73018266982:web:004afa37bcee62a727e4a7',
    messagingSenderId: '73018266982',
    projectId: 'tiktokclone-c2cf7',
    authDomain: 'tiktokclone-c2cf7.firebaseapp.com',
    storageBucket: 'tiktokclone-c2cf7.appspot.com',
    measurementId: 'G-V10JC8M3J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMTGscsQ5USdDALZlIF9NN4jh3m6gOGbw',
    appId: '1:73018266982:android:e89f7e39f607dd7c27e4a7',
    messagingSenderId: '73018266982',
    projectId: 'tiktokclone-c2cf7',
    storageBucket: 'tiktokclone-c2cf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKHzxA9ekBNoEPQUmY66xpDvIjVz91R_o',
    appId: '1:73018266982:ios:1d984e25530df55827e4a7',
    messagingSenderId: '73018266982',
    projectId: 'tiktokclone-c2cf7',
    storageBucket: 'tiktokclone-c2cf7.appspot.com',
    iosClientId: '73018266982-55cpe0se5c9c6k6mosk8mocja8oejnie.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKHzxA9ekBNoEPQUmY66xpDvIjVz91R_o',
    appId: '1:73018266982:ios:1d984e25530df55827e4a7',
    messagingSenderId: '73018266982',
    projectId: 'tiktokclone-c2cf7',
    storageBucket: 'tiktokclone-c2cf7.appspot.com',
    iosClientId: '73018266982-55cpe0se5c9c6k6mosk8mocja8oejnie.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
